FROM grafana/grafana:latest
COPY configs/grafana-datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY configs/grafana-dashboard-provider.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY configs/dashboards /var/lib/grafana/dashboards
